services:
  - type: web
    name: epixel
    region: omaha
    plan: free
    env: node
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: SUPABASE_URL
        fromSecret: SUPABASE_URL
      - key: SUPABASE_ANON_KEY
        fromSecret: SUPABASE_ANON_KEY
      - key: PORT
        value: 10000
